# Generated by Django 3.2.18 on 2023-09-13 14:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=256, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=256, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=256, verbose_name='ОГРН')),
                ('okpo', models.CharField(max_length=256, verbose_name='ОКПО')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('supervisor', models.CharField(max_length=256, verbose_name='Руководитель')),
                ('regestration_date', models.DateField(default=datetime.date(2023, 9, 13), verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256, verbose_name='Номер')),
                ('date', models.DateField(default=datetime.date(2023, 9, 13), verbose_name='Дата оформления')),
                ('total_price', models.IntegerField(blank=True, verbose_name='Полная стоимость')),
                ('total_nds_price', models.IntegerField(blank=True, verbose_name='Полная стоимость с учётом НДС')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('document_type', models.CharField(max_length=256, verbose_name='Тип категории')),
            ],
            options={
                'verbose_name': 'Категория документа',
                'verbose_name_plural': 'Категории документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date', models.DateField(default=datetime.date(2023, 9, 13), verbose_name='Дата')),
                ('time', models.TimeField(default=datetime.time(19, 42, 24, 867883), verbose_name='Время')),
            ],
            options={
                'verbose_name': 'История документа',
                'verbose_name_plural': 'Истории доментов',
            },
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('status_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='ID статуса')),
            ],
            options={
                'verbose_name': 'Статус документа',
                'verbose_name_plural': 'Статусы документов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('units', models.CharField(max_length=256, verbose_name='Единицы измерения')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('nds', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='НДС')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
