# Generated by Django 3.2.18 on 2023-09-13 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='total_nds_price',
        ),
        migrations.AddField(
            model_name='document',
            name='total_nds',
            field=models.IntegerField(blank=True, default=0, verbose_name='НДС в рублях'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='total_price',
            field=models.IntegerField(blank=True, verbose_name='Полная стоимость с учётом НДС'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='time',
            field=models.TimeField(default=datetime.time(19, 59, 57, 622555), verbose_name='Время'),
        ),
    ]
