# Generated by Django 3.2.18 on 2023-09-13 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20230913_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='total_nds',
            field=models.IntegerField(blank=True, null=True, verbose_name='НДС в рублях'),
        ),
        migrations.AlterField(
            model_name='document',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Полная стоимость с учётом НДС'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='time',
            field=models.TimeField(default=datetime.time(20, 0, 31, 555664), verbose_name='Время'),
        ),
    ]
