# Generated by Django 3.2.18 on 2023-09-13 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20230913_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='annuled',
            field=models.BooleanField(default=False, verbose_name='Документ аннулирован'),
        ),
        migrations.AddField(
            model_name='document',
            name='signed',
            field=models.BooleanField(default=False, verbose_name='Документ подписан'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='time',
            field=models.TimeField(default=datetime.time(21, 38, 28, 738690), verbose_name='Время'),
        ),
    ]
