# Generated by Django 3.2.18 on 2023-09-13 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20230913_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenthistory',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Документ согласован'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='time',
            field=models.TimeField(default=datetime.time(21, 42, 12, 553764), verbose_name='Время'),
        ),
    ]
