# Generated by Django 3.2.18 on 2023-09-13 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20230913_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, related_name='documents_history', to='documents.DocumentHistory', verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='time',
            field=models.TimeField(default=datetime.time(21, 46, 40, 61863), verbose_name='Время'),
        ),
    ]
