# Generated by Django 3.2.18 on 2023-09-14 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20230913_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contractor_categories',
            field=models.JSONField(default={}, verbose_name='Категории контрагентов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='regestration_date',
            field=models.DateField(default=datetime.date(2023, 9, 14), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 14), verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 14), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='time',
            field=models.TimeField(default=datetime.time(16, 46, 23, 327075), verbose_name='Время'),
        ),
    ]
