# Generated by Django 3.2.18 on 2023-09-14 13:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0012_auto_20230914_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenthistory',
            options={'verbose_name': 'История документа', 'verbose_name_plural': 'Истории документов'},
        ),
        migrations.AlterField(
            model_name='document',
            name='creator',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель документа'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='time',
            field=models.TimeField(default=datetime.time(18, 10, 1, 975249), verbose_name='Время'),
        ),
    ]
