# Generated by Django 3.2.18 on 2023-09-14 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20230914_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='name',
            field=models.CharField(default='nothing', max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='time',
            field=models.TimeField(default=datetime.time(23, 7, 12, 860885), verbose_name='Время'),
        ),
    ]
