# Generated by Django 3.2.18 on 2023-09-14 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20230914_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='inn',
            field=models.CharField(max_length=256, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='kpp',
            field=models.CharField(max_length=256, unique=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='ogrn',
            field=models.CharField(max_length=256, unique=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='okpo',
            field=models.CharField(max_length=256, unique=True, verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='regestration_date',
            field=models.DateField(default=datetime.date(2023, 9, 15), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 15), verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 15), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='time',
            field=models.TimeField(default=datetime.time(1, 40, 47, 145799), verbose_name='Время'),
        ),
    ]
