# Generated by Django 3.2.18 on 2023-09-15 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20230915_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='okpo',
            field=models.CharField(default='11111', max_length=256, verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='supervisor',
            field=models.CharField(default='None', max_length=256, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='time',
            field=models.TimeField(default=datetime.time(5, 45, 3, 459432), verbose_name='Время'),
        ),
    ]
